"""
Django settings for crypto_server project.

Generated by 'django-admin startproject' using Django 1.10.8.

For more information on this file, see
https://docs.djangoproject.com/en/1.10/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.10/ref/settings/
"""

import os


# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.10/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '&ba@d9z4^5px0nlb=mal1n)-!(i$zj9%=ckhvjd502kt%0ynrt'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
	'localhost',
	'127.0.0.1',
	'192.168.9.175',
]

# Logger
LOGGER_CONFIG = {
	'sentry_dsn': 'https://97fa6e6c3d74471f9a7d7fc6d2e58338:3fc0833f2d8c4a3e840ef679fe197da9@sentry.aqumon.com/21',
	'log_dir': os.path.join(BASE_DIR, 'log'),
	'release_sha': '__release_sha__'
}

# Application definition

INSTALLED_APPS = [
	# 'django.contrib.admin',
	# 'django.contrib.auth',
	# 'django.contrib.contenttypes',
	# 'django.contrib.sessions',
	# 'django.contrib.messages',
	# 'django.contrib.staticfiles',
	'raven.contrib.django.raven_compat',
	'crypto_server.apps.CryptoServerConfig'
]

MIDDLEWARE = [
	# 'django.middleware.security.SecurityMiddleware',
	# 'django.contrib.sessions.middleware.SessionMiddleware',
	'django.middleware.common.CommonMiddleware',
	# 'django.middleware.csrf.CsrfViewMiddleware',
	# 'django.contrib.auth.middleware.AuthenticationMiddleware',
	# 'django.contrib.messages.middleware.MessageMiddleware',
	# 'django.middleware.clickjacking.XFrameOptionsMiddleware',
	'raven.contrib.django.middleware.SentryMiddleware',
]

ROOT_URLCONF = 'crypto_server.urls'

TEMPLATES = [
	{
		'BACKEND': 'django.template.backends.django.DjangoTemplates',
		'DIRS': [],
		'APP_DIRS': True,
		'OPTIONS': {
			'context_processors': [
				'django.template.context_processors.debug',
				'django.template.context_processors.request',
				'django.contrib.auth.context_processors.auth',
				'django.contrib.messages.context_processors.messages',
			],
		},
	},
]

WSGI_APPLICATION = 'crypto_server.wsgi.application'

# Database
# https://docs.djangoproject.com/en/1.10/ref/settings/#databases

DATABASES = {
	'default': {
		'ENGINE': 'django.db.backends.sqlite3',
		'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
	}
}

# Password validation
# https://docs.djangoproject.com/en/1.10/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
	{
		'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
	},
	{
		'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
	},
	{
		'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
	},
	{
		'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
	},
]

# Internationalization
# https://docs.djangoproject.com/en/1.10/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Hong_Kong'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.10/howto/static-files/

STATIC_URL = '/static/'

API_KEY = 'QVaoiTN1DwGxGVvWoHXXDDFh3UVhlH73XySG4rD3hpNfiGW3Izd6UeoWt1uKe1Tf'
API_SECRET = 'bqS1yeiuX3xv8HBWb0DsptQ3VvHGGyQQ99YPEw8yMeWpAUGnMH3G4MULxj6vHqbd'

ACCESS_TOKEN = 'dX8mPbl4RdY4UqzF2FGd'

BITMEX_KEY = 'z_TX-uRWKjr7oIgVEhDtiWeg'
BITMEX_SEC = 'whHxwsd_E5uHIOLmjvoMf_pHksYHUR22NLrhfetshptZe6rM'